### PR TITLE
Enabling checks on unacceptable ciphers

### PR DESCRIPTION
**Pull request by jsane**
Reverting your changes and enabling checks to detect weak ciphers. Have submitted a PR on puppet-agent to disable ciphers per the recommendations from SSL Implementation Reference document. 
Shout if I have messed anything :-)

### CODE REVIEW

**Comment by jsane** [comment]
I changed the commit message to "(SEC-13) ..." on my branch. However github won't give me an option to submit a PR with it. Assuming this PR still holds and will see the updated commit message on my branch.

**Comment by joshcooper** [comment]
This has the potential to break any PE release that is testing against an older puppet-agent build, whose openssl compile options haven't been fixed. Going to hold off on merging this until @jsane is back.

**Comment by jsane** [comment]
Hi @joshcooper and also including @jpartlow 

Do you see any harm in merging the changes to disable weak ciphers in openssl to older versions of puppet-agent. Presently it is in master and 5.0.x. How far do we need to go back beyond 1.10.x? To answer myself, I would think we may need to go back till when we started vendor-ing openssl. 
I am aware of the oddity with weak-cipher-disabled version of openssl still showing 3DES being enabled, as you noted in SEC-51, but it does not get presented in the client hello (was tested with this PR). I will be investigating that separately. 
In meantime doing this change in nogotofail can actually help us catch/surface any instances where any of our clients attempts sending in 3DES (after we merge the openssl changes in all prior puppet agents).  Pl let me know.

**Comment by joshcooper** [comment]
I'm not sure about 1.10.x... I think it depends how long we plan to support it. /cc @branan

**Comment by jsane** [comment]
Hi @branan 
What are your thoughts about integrating changes in openssl for disabling some weak ciphers in 'older' versions of puppet agent like 1.10.x? That way we can then enable testing for them uniformly in nogotofail per this PR: https://github.com/puppetlabs/nogotofail/pull/1. Other option would be to create branches in nogotofail corresponding to those for puppet repo so the latest 5.x versions of agent can benefit from the weak cipher checking in nogotofail. 
thanks

**Comment by joshcooper** [comment]
Going to close this due to inactivity. We can reopen if needed later.

**Pull request closed without merging**
