### PR TITLE
(PE-16491) Adding expired certificate connection handler

### PR DESCRIPTION
**Pull request by jsane**
To allow testing expired server and CA certificate(s) from pe_acceptance_test's client_tls_verification test script.

### CODE REVIEW

**Comment by jsane** [comment]
@joshcooper Could you pl review this. Chris T merged my other PR on pe_acceptance_test for this ticket but w/o this the other won't be useful (wonder how things have not broken yet). I intentionally decided to introduce a new handler instead of re-using invalidhostname to keep things clean and separate so their purposes are clear.

**Review by RandellP — APPROVED** [review]
This looks fine to me.  I am no expert of course, but it doesn't look like it could cause problems on it's own, so i am happy to merge if you like.

**Comment by jsane** [comment]
Yes please. By itself it should not cause any problems; whoever needs to explicitly invoke this attack handler unlike data handlers which execute by default. thanks

**Review by MikaelSmith — APPROVED** [review]
Looks ok. My assumption is this is a completely new test type we wanted to add.

**Pull request merged**
